services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.1.3.5
    container_name: test-clickhouse
    restart: always
    environment:
      - "CLICKHOUSE_DB=other"
    volumes:
      - "test-clickhouse:/var/lib/clickhouse/"
    ports:
      - "127.0.0.1:9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  test-clickhouse:
    name: test-clickhouse
networks:
  default:
    name: clickhouse-net
